title: Journey to the Code blog
description: I want to build my own blog, so this is it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

#infor
fullname: Tom Dinh
#twitter_username: 'tomdinhnz'
twitter_link: https://twitter.com/tomdinhnz
github_username:  tom031
github_link: https://github.com/tom031
linkedin: https://linkedin.com/in/tomdinhnz
skype: tomdinhnz
emailEncoded: "String.fromCharCode(116,111,109,100,105,110,104,110,122,64,103,109,97,105,108,46,99,111,109)"
sof: https://stackoverflow.com/users/6716449/tom031
slideshare: http://www.slideshare.net/dinhmanhhoang

#External resources
disqus: journeytothecode-blog
google_analytics: UA-90471948-1
avatar: http://s.gravatar.com/avatar/31793858d3a0ca4af25a1feb8b50a498?s=60


#default setting for Front Matter
defaults:
  - scope:
      path: posts # default setting for Front Matter for all posts
      type: posts
    values:
      layout: post
      title: Tom Blog
      permalink: ""
      published: ""
      date : 2017-1-1
      category: blog
      categories: jekyll, github, pages
      tags: code


# Build settings
icons_link: images/icons/
favicon: /favicon.ico
markdown: kramdown
paginate: 5
paginate_path: /pages/page:num/
theme: minima
highlighter: rouge
permalink: pretty #permalink in the front matter of your blog page will cause pagination to break
version: 1.0.1
encoding: utf-8
environment: production
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate

