title: Tom's journey to the Code
description: I want to build my own blog, so this is it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

#infor
fullname: Tom Dinh
twitter_username: tomdinhnz
twitter_link: https://twitter.com/tomdinhnz
github_username:  tom031
github_link: https://github.com/tom031
linkedin: https://linkedin.com/in/tomdinhnz
skype: tomdinhnz
email: tomdinhnz@gmail.com
sof: https://stackoverflow.com/users/6716449/tom031
slideshare: http://www.slideshare.net/dinhmanhhoang

#External resources
disqus: tom031-github-blog
google_analytics: UA-90471948-1
avatar: http://s.gravatar.com/avatar/31793858d3a0ca4af25a1feb8b50a498?s=60


#default setting for Front Matter
defaults:
  - scope:
      path: posts # default setting for Front Matter for all posts
      type: posts
    values:
      layout: post
      title: Tom Dinh's Blog
      permalink: ""
      published: false
      date : 2017-1-1
      category: blog
      categories: jekyll, github, pages
      tags: code


# Build settings
favicon: /images/favicon.ico
markdown: kramdown
paginate: 5
paginate_path: /pages/page:num/
theme: minima
highlighter: rouge
permalink: /posts/:title #permalink in the front matter of your blog page will cause pagination to break
version: 1.0.1
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
