title: Tom's journey to the Code
description: I want to build my own blog, so this is it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

#infor
fullname: Tom Dinh
twitter_username: tomdinhnz
twitter_link: twitter.com/tomdinhnz
github_username:  tom031
github_link: github.com/tom031
linkedin: linkedin.com/in/tomdinhnz
skype: tomdinhnz
email: tomdinhnz@gmail.com
sof: stackoverflow.com/users/6716449/tom031

#External resources
disqus: tom031-github-blog
google_analytics: UA-90471948-1
avatar: http://s.gravatar.com/avatar/31793858d3a0ca4af25a1feb8b50a498?s=60


#default setting for Front Matter
defaults:
  -
    scope:
      path: "posts" # default setting for Front Matter for all posts
      type: ""
    values:
      author: "Tom Dinh"
      layout: "post"
      title: "Tom Dinh's Blog"
      permalink: ""
      published: "false"
      date : "2017-1-1"
      category: "blog"
      categories: jekyll, github, pages
      tags: "code"


# Build settings
favicon: /images/favicon.ico
markdown: kramdown
theme: minima
highlighter: rouge
permalink: /posts/:year/:month/:day/:title/
gem:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
