title: Tom's journey to the Code
description: Development journey of Tom
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

#infor
fullname: Tom Dinh
twitter_username: tomdinhnz
twitter_link: twitter.com/tomdinhnz
github_username:  tom031
github_link: github.com/tom031
linkedin: linkedin.com/in/tomdinhnz
skype: tomdinhnz
email: tomdinhnz@gmail.com
sof: stackoverflow.com/users/6716449/tom031
avatar: http://s.gravatar.com/avatar/31793858d3a0ca4af25a1feb8b50a498?s=60


#default setting for Front Matter
defaults:
  -
    scope:
      path: "posts" # default setting for Front Matter for all posts
      type: "posts"
    values:
      author: "Tom Dinh"
      layout: "post"
      title: "Tom Dinh's Blog"
      permalink: ""
      published: "false"
      date : "2017-1-1"
      category: "blog"
      categories: jekyll, github, pages
      tags: "code"

# Build settings
disqus: tom031
markdown: kramdown
theme: minima
highlighter: pygments
permalink: /posts/:year/:month/:day/:title/
gem:
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
